version: '3.8'

x-worker-template: &worker-template
  build:
    context: .
  entrypoint: celery
  command: -A celery_app.app worker --loglevel=info
  volumes:
    - ./core:/core
    - ./core/static:/static
  depends_on:
    - redis
    - database
  environment:
    - DB_HOST=database
    - DB_NAME=dbname
    - DB_USER=dbuser
    - DB_PASS=password

services:
  web-app:
    build:
      context: .
    ports:
      - "8002:8002"
    volumes:
      - ./core/static:/static/
      - ./core:/core
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password
    command: >
      sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:8002"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: -p 5433

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    ports:
      - "6380:6380"
    command: --port 6380

  worker1:
    <<: *worker-template
    hostname: worker1
  worker2:
    <<: *worker-template
    hostname: worker2

volumes:
  db_data:
