version: '3.8'

services:
  web-app:
    build:
      context: .
    ports:
      - "8001:8001"
    volumes:
      - ./core:/core
    environment:
      - DB_HOST=localhost
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password
      - IS_DEBUG=True
      - REDIS_URL=redis://localhost:6379/0
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8001"
    depends_on:
      - database
      - redis
    network_mode: "host"

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: -p 5433
    network_mode: "host"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    ports:
      - "6380:6380"
    command: --port 6380
    network_mode: "host"

volumes:
  db_data:
