version: '3.8'

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./core:/core
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password
      - IS_DEBUG=True
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5433"
    volumes:
      - db_data:/var/lib/postgresql/data
    command: -p 5433

  redis:
    image: redis:7.0.5-alpine
    hostname: redis
    ports:
      - "6380:6380"
    command: --port 6380

volumes:
  db_data:
