# Generated by Django 5.1.1 on 2024-10-09 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='refresh_token',
        ),
    ]
