# Generated by Django 5.1.1 on 2024-10-10 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('users', models.ManyToManyField(help_text='connection with User', related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('access_weight', models.PositiveSmallIntegerField(choices=[(0, 'Owner'), (1, 'Setting up project parameters'), (2, 'Executing and assigning tasks'), (3, 'Executing tasks'), (4, 'Observer')], default=0, help_text='access level for the position')),
                ('company', models.ForeignKey(help_text='connection with Company', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='company.company')),
                ('users', models.ManyToManyField(help_text='connection with User', related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Project',
                'ordering': ['access_weight'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(help_text='connection with Company', on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='company.company')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_access_weight', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Setting up project parameters'), (2, 'Executing and assigning tasks'), (3, 'Executing tasks'), (4, 'Observer')], help_text='access level for the position', null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_positions', to='company.position')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_projects', to='company.project')),
            ],
            options={
                'verbose_name': 'Project Position',
                'verbose_name_plural': 'Project Positions',
            },
        ),
        migrations.AddField(
            model_name='position',
            name='projects',
            field=models.ManyToManyField(help_text='connection with Project', related_name='positions', through='company.ProjectPosition', to='company.project'),
        ),
    ]
