# Generated by Django 5.1.1 on 2024-12-17 09:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['access_weight'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='rgb(188,219,174)', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_of_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'High'), (1, 'Medium'), (2, 'Low')], default=1, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(help_text='connection with User', related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(default='Owner', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(help_text='connection with Company', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='company.company'),
        ),
        migrations.AlterField(
            model_name='projectposition',
            name='project_access_weight',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Setting up project parameters'), (2, 'Executing and assigning tasks'), (3, 'Executing tasks'), (4, 'Observer'), (5, 'Standard')], default=5, help_text='access level for the position'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='rgb(196,177,194)', max_length=20)),
                ('owner', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.ForeignKey(help_text='connection with Company', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company')),
                ('parent', models.ForeignKey(blank=True, help_text='connection with department parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='company.department')),
                ('users', models.ManyToManyField(help_text='connection with User', related_name='departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='departments',
            field=models.ManyToManyField(help_text='connection with Department', related_name='departments', to='company.department'),
        ),
    ]
