# Generated by Django 5.1.1 on 2024-10-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_position_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['access_weight'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterField(
            model_name='projectposition',
            name='project_access_weight',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Setting up project parameters'), (2, 'Executing and assigning tasks'), (3, 'Executing tasks'), (4, 'Observer')], default=None, help_text='access level for the position', null=True),
        ),
    ]
