# Generated by Django 5.1.1 on 2024-12-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_position_options_project_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='owner',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(default='rgb(205,192,196)', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='rgb(175,213,215)', max_length=20),
        ),
    ]
