# Generated by Django 5.1.1 on 2024-12-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_department_owner_alter_department_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(default='rgb(181,172,205)', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='rgb(209,210,208)', max_length=20),
        ),
    ]
