# Generated by Django 5.1.1 on 2025-01-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_department_color_alter_project_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(default='rgb(185,206,207)', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='access_weight',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Owner'), (2, 'Setting up project parameters'), (3, 'Executing and assigning tasks'), (4, 'Executing tasks'), (5, 'Observer')], default=1, help_text='access level for the position'),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='rgb(181,162,218)', max_length=20),
        ),
    ]
