# Generated by Django 5.1.1 on 2024-10-28 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_project_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(help_text='connection with Company', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='company.company')),
                ('parent', models.ForeignKey(blank=True, help_text='connection with department parent', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='company.department')),
                ('users', models.ManyToManyField(help_text='connection with User', related_name='departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
    ]
