# Generated by Django 5.1.1 on 2024-10-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_projectposition_project_access_weight'),
        ('company', '0006_department'),
    ]

    operations = [
    ]
