# Generated by Django 5.1.1 on 2024-11-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_merge_20241030_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(default='rgb(0,0,0)', max_length=20),
        ),
    ]
