# Generated by Django 5.1.1 on 2024-11-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_department_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(default='rgb(169,209,220)', max_length=20),
        ),
    ]
