# Generated by Django 5.1.1 on 2024-11-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_department_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(default='rgb(0,0,0)', max_length=20),
        ),
    ]
