# Generated by Django 5.1.1 on 2024-12-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_department_color_alter_department_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='color',
            field=models.CharField(default='rgb(169,185,199)', max_length=20),
        ),
    ]
