name: Django Testing

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run docker-compose
      run: |
        docker compose -f docker-compose.yml build
    - name: Make Migrations
      run: |
        docker compose -f docker-compose.yml run --rm web-app sh -c "python manage.py makemigrations"
    - name: Run Migrate
      run: |
        docker compose -f docker-compose.yml run --rm web-app sh -c "python manage.py migrate"
    - name: Run Tests
      run: |
        docker compose -f docker-compose.yml run --rm web-app sh -c "python manage.py test"
